---
title: "Introduction to RAG"
draft: true
author: "Sushrut"
date: 2026-04-20
description: ""
categories: [GenAI, "RAG"]
tags: [GenAI, "RAG", "Blog"]
format:
  html:
    link-citations: true
    smooth-scroll: true
    math: mathjax
    toc: true
    fig-format: svg
    mermaid:
      theme: dark
bibliography: ../../../references/references.bib
csl: ../../../references/apa.csl
execute:
  enabled: true
  fig-format: svg
---

Before beginning this post let's briefly discuss what we are going to have a look at. We will start first with LLMs and discuss their basic working and then gradually discuss what problems we face and How RAG solves these problems. We will discuss it from first principles and pretend as if we are inventing RAG.

We will go through a pretty straightforward approach. We will first identify the problems and then discuss how we will solve them. We will follow the simple yet effective why-what-how approach where we will initially discuss:

1. why RAG is important
2. what is RAG
3. how RAG is implemented

We will again mostly be seeing this in an overview perspective instead of going deep. We will go deep into RAG in future blog posts but for this post we will be in overview mode.

# Why is RAG Important?

## Introduction

You might recall that in the month of November of 2022, ChatGPT was launched by OpenAI. This took all of us by surprise because it could answer any sort of question from any kind of domain and it would answer it very quickly and reliably. This was one of the first reliable chatbots developed with the help of deep learning AI models. This software or application was intelligent, powerful, and fast irrespective of whether the domain is technology, coding, finance, healthcare, or any other domain. ChatGPT derived all this power and knowledge from the underlying model that it was using, which was the GPT model, which is based on the transformer architecture which is a deep learning model. And the biggest power of the transformer architecture is its self-attention mechanism. In a nutshell, the self-attention mechanism helps with the following: It helps us understand and learn the inherent patterns in any language. However as with any deep learning model, it is not just the architecture which gives the model such predictive power. It also depends on how the training of the model was done. These large language models or LLMs, of which GPT is an example, are trained on massive textual data sets. The part "language model" in large language models or LLMs comes from the fact that these models are trained on language or textual data. The word "large" comes from the fact that these models have billions or even trillions of parameters (weights and biases). The "language" part comes from the fact that once these models are trained on large text data, it acquires a skill called Natural Language Understanding or NLU for short. So once the model is trained on massive textual data, it picks and learns the patterns present in the language and its distribution. Using these patterns, it can now generate new text. This is how it develops this generative capacity. This is clearly evident by how an LLM responds. For example you must have seen how ChatGPT replies to our questions as if some other person is replying so it seems like we are talking to another human being.

During training of an LLM the data used is the entire internet data, e.g., articles, books, webpages, blog posts, code repositories, and much more. The training process is so comprehensive and massive that it can last for weeks or even months at a time. The training process is quite expensive in terms of the computational power, the skilled manpower required, the massive storage facilities and infrastructure required, and the energy costs as well. This training is called as pre-training.

I mentioned that a large language model learns or picks out patterns present in the language. How does it store this skill that it has picked up the patterns? It stores the skill in the parameters that I talked about earlier. These parameters are the weights and biases of the model. So these parameters actually store the knowledge the model has acquired during training. These parameters tell the model how language works, what is the grammar of the language, what is the syntax of the language, what is the semantics of the language, what are the common phrases used in the language, what are the common knowledge, what is the general knowledge as well. These parameters store the patterns and distributions of the language.

Although from the training process it seems like LLMs have learned some very complex skill, in essence what LLMs do is predict the next word. So they are next-word predictors. Once a user enters a particular text (more technically called as a prompt) as the input to this LLM, the LLM's job is to predict the next word, the next most likely word that can be put in the sequence. The LLM does this job recursively. For example the predictions given by the LLM are appended to the user's input and the entire appended string is passed into the LLM again. The LLM predicts the new word and this process goes on and on until the LLM predicts the end of the sequence. For example if you give input as "Hello my name is Sushrut and I am " the LLM might predict "23", then the input becomes "Hello my name is Sushrut and I am 23" then the LLM might predict "years", then the input becomes "Hello my name is Sushrut and I am 23 years" and so on. This process of next-word prediction is recursive and is the basis of how LLMs generate text. This is also quite evident if you have used ChatGPT. You must have seen how the output of ChatGPT is shown in a streaming fashion, word by word. So we can say that the key focus of any LLM is trying to complete the prompt given by the user as input as accurately and fluently as possible.

After the pre-training process we would want to serve these models to our users. The user will input a query or a prompt to this model and the model will generate a response. This entire process of the prompt going into the model and generating a response is technically called model inference. However the users, after using the model for some time, identified a few problems and it's working. Our technical team identified four such problems. Let's discuss these problems in some detail.

## Four Problems in LLMs

### Knowledge Cutoff

As mentioned earlier during the pre-training phase of the model, the data used is from the entire internet and the data is massive. I also mentioned that this pre-drink phase can last for weeks or even months for some very large models. Recall how you train a simple artificial neural network. We first decide on an architecture, which is not exactly a part of the training process. It's something we decide prior to the training. Once the architecture is decided then we initialize the weights and sometimes these weights are initialized randomly. Then you start the training loop in which you perform four steps. The first step is known as forward propagation, in which using the current weights of the model, you do a prediction. In the next step you calculate the loss. Once this loss is calculated, we carry out back propagation using this loss and find out the gradients of all the parameters of the model with respect to this loss. And in the final step we update the weights of all these parameters using the gradients that we found in the previous step. Finally once the model is trained, we evaluate it. So these are the four steps which are carried out during the training process of any artificial neural network and it's the same with large language models as well. The pre-training step involves these four steps only and it's these four steps that take a long time, weeks up to months, for complex models. And just like how during training an artificial neural network we do not change the data, the same is true even for LLMs. During the pre-training phase of an LLM the data is not changing; it's static. Say we start the training process or the pre-training process of an LLM in August of 2025 and the training data used is upto July of 2025. And say we are training a very large language model which takes months of training and say we complete the pre-training process in December of 2025. And once this LLM is trained, we decide on deploying it for the public in February of 2026 after thorough testing. The model is performing well. Users are happy and everything seems to be going well. However after some time users notice that if the model is asked about any event that happened after July of 2025, the model does not generate a proper result. This is because the training data for this LLM does not include any data after July of 2025. This is a problem known as knowledge cutoff.

Now a naive approach that someone might suggest to tackle this problem is to just train the model every day so that the model is always making predictions based on the data that is always up to date. Obviously this is not possible because, as I mentioned earlier, the training time or the time taken during the pre-training phase of the model can range from weeks to months. Training the model on up-to-date data is just not computationally feasible. All LLM models have a knowledge cutoff date which is specific to the model. So, models are frozen in time. It cannot access recent information just using its parameters.

### Hallucinations

In simple terms what we mean when we say that a model is hallucinating is the following: the model generates false facts but it does so with full confidence. It seems as if the response generated by the model is legit but in reality it is garbage. For example consider you are working on an academic problem which is at the cutting edge of a particular field and you identify that you have a knowledge gap about a particular topic. What you do is you ask the LLM to search whether there are any publications or papers that are published which answer the knowledge gap you have. It may happen that the LLM will generate the abstract of a paper that does not exist, which is addressing the knowledge gap you have. It may also happen that it quotes a sentence from a paper that does not exist. In both the cases, the model is generating false information but it does so with full confidence. This is known as hallucination.

This happens because, recall what I mentioned earlier, any large language model has acquired the skill of natural language understanding. Which means it can generate text given an input prompt. The model will generate a text irrespective of whether it is true or false if the user has given an input prompt. So we say that a model is hallucinating when it is generates plausible but false information confidently.

### No Source Attribution

So whenever an LLM is given a query by the user, it will generate a response. The problem is that when the model generates this response, it doesn't provide any information about where it found information to generate that response. What are the resources based on which it generated this response? There is no mention of any such resources in its response. This happens because the data given to the model during pre-training doesn't contain its sources as it is irrelevant for the next-word prediction task. So, an LLM cannot verify or trace where the information it is generating came from.

### No Private Data Access

Now, consider an example of a user who is asking an LLM about some policy of a company they are working in. In this case, the LLM will not be able to respond to this person because it is not trained on the company data. This is because the data given to the model during pre-training doesn't include any information about any private company or private data. The model can only respond based on the data stored in its parameters, which is also known as parameterized knowledge. So, an LLM cannot access company/proprietary documents.

## Adding Information to the Context and Context Window

We have discussed about the problems we face while working with LLMs. Now let's discuss about how can we solve them.

The root cause of the first two and the last problem is that the dataset used during the pre-training phase is static. We cannot really dynamically update the data during training. So, we need to figure out a way to give outside information to the model after training based on which it can generate accurate output. In other words, we want to give the model some additional external knowledge apart from its parametric knowledge that it acquired during its training.

Even when it comes to the third problem of no source attribution, the reason is that there is information about the source in the parametric knowlege of the model. Again, if we could add on the source information to the model externally, then we can make sure that the model also provides the source information of the output it is generating.

This is also true with the no private data access problem. The reason is that the data given to the model during pre-training doesn't include any information about any private company or private data. So, we cannot really train the model on private data. We can only make the model to have access to private data at the time of inference. So, we need to figure out a way to give outside information to the model at the time of inference based on which it can generate accurate output.

The parametric knowledge and the external knowledge passed to the model together is known as the context of the model. In simple terms what context means is what the model currently knows.

Is adding external knowledge to the LLM the only way to solve these problems? No, there are other ways as well. Let's discuss a few of them now.

## Other Techniques

### Prompt Engineering

What we do in prompt engineering is that we try to give external knowledge to the model right in the input prompt itself. Consider the example of private data. If a user named "Sushrut" asks the model, "What is my name?", the model will not be able to answer this question because it doesn't have any information about the user. However, if the user says in the first message, "Hi, my name is Sushrut", and the model replies "Hello Sushrut, how can I help you?", and then the user asks "What is my name?", but while asking this question the user also provides the entire chat history they have with the model in the input prompt, then the model can answer this question. The user engineered their prompt correctly so that it gives enough external knowledge, or context, to the LLM to provide an accurate answer. This property of the model of learning what it should respond to a user's prompt using its context which includes external data is known as in-context learning (ICL). The model doesn't learn this property during training. Instead, it learns this property at the time of inference.

The model first tries to generate an answer based on its parameterized knowledge. If it doesn't have the answer, it then searches for the answer in the context provided by the user. So, in prompt engineering, the external knowledge is provided by the user in the input prompt itself.

An advantage of prompt engineering that it is very fast and simple to use. The user can very easily provide some knowledge in the input prompt.

### Fine-tuning

What happens in fine-tuning is that you try to retrain the model but you don't train all the parameters. You select a small subset of the parameters which you train based on your custom data. There are many techniques using which you can carry out fine-tuning. Some of them are PEFT, LoRa, and QLoRa. Generally fine-tuning is not used to update the knowledge of the model. It is mostly used to change or update the way it responds to the prompts given by the user. Hence it is mostly used in the healthcare or legal domain where the language matters.

Some drawbacks of Fine-Tuning are that it requires computational power (not as much as the pre-training phase but still there is a considerable requirement of computational power) and also we need expertise to do it. It is definitely not as simple as prompt engineering and ICL.

So ICL is a really strong candidate to solve these problems. We simply have to provide the model with all the necessary information it needs in the input prompt. However there is still a problem. Consider the example of the legal domain. We can't really upload large documents in the context. There is a limit on the context size which is also known as the context window. Recall that these allells behind the scenes have transformer architecture which works on attention mechanism. So if the input prompt is very very large, it will be quite difficult for this mechanism to learn patterns in between the words present in the input. This is exactly the reason why every LLM has a limited context window. Some models have a context window of 200,000 tokens (roughly a word is made of 1.3 tokens on an average), and some complex models have a context window of 1 million tokens. This means that the input prompt cannot exceed 1 million tokens. Another problem is that if the context window is, say, one million tokens, we cannot fill up the entire one million token window because if we do that another problem occurs which is known as the "lost in the middle" problem. What happens in this problem is that the LLM focuses more on what comes at the beginning of the prompt and towards the end of the prompt, and whatever comes in between is sort of ignored. For example, if we are able to fill 1000 pages worth of information within the context, the LLM might not be able to recall the information present in the middle 700 or so pages. The information present in the middle might be very very important for the LLM to generate accurate information.

To solve the four problems that we talked about, we need to devise a method such that only the required information is given to the model in its context which is important for answering the prompt given as input to the model. We can store all the external data in some centralized knowledge base and try to dynamically give only the required subset from that knowledge base to the model in its context which is necessary for the model to generate an accurate response. We need a way to filter the relevant information from the knowledge base. This is roughly what is known as Retrieval Augmented Generation (RAG).

# What exactly is RAG?

So as we discussed every LLM has four problems, which are:

1. Knowledge cut-off
2. hallucinations
3. no source attribution
4. no access to private data

To solve these problems we discussed that in-context learning, or ICL for short, would be the best solution, combined with a filtered context which sits well within the context window associated with the LLM. Retrieval Augmented Generation, or RAG for short, is a solution that helps us achieve this. Let's now discuss each of the words in "Retrieval Augmented Generation".

The word "generation" is used because the LLM uses its generative AI capability to generate the answer. Now let's discuss the word "retrieval". Recall that we discussed that we store the entire knowledge or information we have inside the database. We can also retrieve this information if required from the database. This retrieval process is dynamic based on the user's input query. Whenever a user inputs a query, it first goes to this knowledge database. Then the searching process happens, which tries to find if there is any knowledge inside the knowledge database which is similar to the input query. This similar knowledge is retrieved from the database and is passed on to the LLM as context along with the user's query. This is how the dynamic filtering of knowledge that we talked about earlier happens. So this database, inside which the knowledge is present, is smart. It only retrieves that information which is relevant to the query asked by the user dynamically. The relevance here is measured in terms of semantic meaning, i.e., the query and the retrieved information is similar in meaning. The information retrieved by the database is also ranked in descending order of this semantic similarity, i.e., the most similar information is at the top and the least is at the bottom. This helps filter further. Now let's discuss the word "augmented". The sort of literal meaning of the word "augmentation" is enhancing. What we did here was, using the retriever, we retrieved some top-$k$ number of documents from the database. Using these documents or this information retrieved, we would like to augment (or enhance) the input prompt given to the LLM. This was the entire idea of in-context learning. So, along with the input prompt given to the LLM by the user, we would also give it external information which comes from the knowledge base. This external knowledge is also filtered based on the input query given by the user. This process of adding external knowledge to the input prompt given by the user is called context assembly. In this process of context assembly only, we are augmenting the user's input prompt which goes to the LLM. The LLM will then use in-context learning to provide us the relevant answer, which is generated by keeping into consideration the external information retrieved from the knowledge base. This helps the LLM better answer the query asked by the user, as it has access to external relevant data relevant to the question asked by the user. As the retrieval process only returns some number of documents, some key number of documents, this also makes sure that the context window of the LLM is not filled up. This also helps with the lost in the middle problem.

# How does RAG work?

Let us now discuss how exactly RAG works and how the input query flows inside the RAG pipeline.

## Components of RAG

We will first discuss about all the components involved in a typical RAG pipeline and then see how they connect with each other using a flowchart.

### Knowledge Source

Note that knowledge source and knowledge base are different. Knowledge base is a database, which we will discuss later. As the name suggests, knowledge source refers to the entire knowledge we have that can be used in answering any question asked by the user. The knowledge source can be in many formats, for example pdf, csv, docx, txt, markdown, html, and also in multi-modal formats like mp4, mkv, mp3, etc. Consider the example of trying to answer a company-related question based on that company's documents. In that case, all the documents about the company can be called the knowledge source. What a RAG pipeline does is it captures all the textual content present in these documents or the knowledge source. An important component used in drag that does this is known as document loader. Document loaders not only load the information in RAM, but they can also parse the information, i.e., read the content while maintaining the structure of the document. For instance, if the knowledge source contains PDF files, then we have a separate document loader type for PDF documents. So document loaders load various types of documents depending on their structure. We also have document loaders for csv, docx, txt, markdown, html, etc. Further document loaders not only load the content of the knowledge source or the documents, it also loads the metadata associated with it, for example, name of the document, its size, type, path, date of creation, etc.

### Chunking

Once the document loader acts on the knowledge source, it has the content of the knowledge source, and it can also pass the knowledge source. As this knowledge source or the documents can be of arbitrarily large size (say 100 pages), what chunking does is it chunks or breaks the knowledge source into small parts. If we use page wise chunking, it will break the 100 page PDF into 100 chunks. So it's like a huge document gets further broken down into smaller documents. In the PDF example, a 100-page PDF document was divided into 100 smaller PDF documents. Their metadata is also stored accordingly.

### Embedding

What we essentially do during embedding is convert text into numbers (a vector) so that the model can understand it. Recall that some common classical NLP techniques that do this are bag of words, TF-IDF, etc. However, embedding is different as deep learning models are used to calculate these numbers. A key characteristic of these models is that they capture the semantic meaning of the text. Instead of focusing on the exact keyword and text, what is more in focus is the underlying meaning and intent of the text. Numbers represent this semantic meaning. During the retrieval process, this semantic meaning is what forms the basis of filtering. So we have an embedded model that converts chunks into numbers or vectors, which store its semantic meaning. Each chunk which corresponds to a particular embedding vector. One thing to keep in mind is that every embedder model has a fixed-dimensional vector output. For example, if an embedder model has an output vector of 128 dimensions, then no matter how long or short the chunk size is, it will always convert it to a 128-dimensional vector.

### Knowledge base

The reason why we are carrying out the document loading, chunking, and embedding processes is that if we are given, say, a 100-page document, then we would want the LLM to help us carry out a question-answer task on those documents. The LLM did not see these documents during its training, and hence whatever knowledge is contained in these documents is not a part of its parameterized knowledge. Which is why we are using in-context learning and a RAG architecture to do this. These three steps (that is, document loading, chunking, and embedding) are actually time-taking. Further, they are also repetitive. If we have a fixed static 100-page document on which we want to carry out this question-answer task, then it doesn't really make sense to carry out these three processes each time a user asks any query to the LLM. So what happens in practice is that once the documents are loaded, chunked, and each of the chunks is created into an embedding vector, all these embedding vectors are stored. Whenever a user asks a query, the similarity score can be calculated efficiently without having to repeat the three processes. The database in which these embedding vectors are stored is called a vector store or a vector database. This database, once populated with all the vectors, is also known as knowledge base. We can also update this knowledge base, as it's just like any other database. We can carry out the same CRUD operations that we can carry out on any database.

Now we don't just store the embedding vectors inside the knowledge base. We also store the corresponding text and its associated metadata. When a user asks any query, their query is converted into an embedding vector using the same embedder model, and similarity scores are calculated based on which only the vectors corresponding to the most similar chunks are retrieved. This also makes sure that we know what the text corresponding to the most similar chunks is as this text is what is going to augment the user prompt. The associated metadata also gives information about the source of the chunks, which helps solve the source attribution problem. Now, when a user asks any query, obviously the query will be in the form of a text. However, the chunks that are stored in the knowledge base are stored in the form of vectors, where each chunk corresponds to one particular vector. What is further stored corresponding to each of these vectors is the text in those chunks and the metadata corresponding to it. The Embedder model is then used to convert the user's query into a vector which is of the same size as the vectors stored in the knowledge base. The similarity score is then calculated with each of the chunk vectors with the vector corresponding to the query given by the user. This similarity score can be distance-based, for example, Euclidean distance. Then the most similar top-$k$ ($k$ is sort of a hyperparameter) chunks are retrieved, and the text corresponding to those chunks is documented in the user's query before passing it on to the LLM as the final augmented prompt. (This paragraph also includes information about other RAG components like retrieval, embedder model, prompt augmentation, etc.) Another guard rail, which is very crucial and which should be added inside the prompt, is the fact that the LLM should not answer the question if it doesn't know the answer. If the augmented prompt (that is, a prompt augmented using the retrieved text corresponding to all the similar chunks) does not provide an answer to the user's question, then the LLM should refuse from answering. If this entire pipeline or workflow works well, then the answer given by the LLM is grounded in the knowledge base or the documents. 

## Revisiting the four problems

Let us now discuss whether using the RAG architecture solves the full problem that we talked about.

1. Knowledge cutoff:
   - We are able to solve the problem of knowledge cut-off using RAG. We simply have to add information about the events that took place after the cutoff date of the LLM in the knowledge base.
2. Hallucination:
   - Recall that the reason why an LLM hallucinates is that it does not have information and context about the query asked by the user. Using RAG, we are essentially grounding the response generated by the allelium in facts. This significantly reduces the chance that the LLM will hallucinate the answer.
3. No source attribution:
   - Recall that the vector store not only stores the embedding vectors but also the text associated with the chunk and the metadata. The metadata contains information about the source.
4. No access to private data:
   - Obviously, as we can provide private data to the LLM in the form of a knowledge base, we have also solved this problem. This means that the user can now also ask questions to the LLM about their own private data.

# Failures in RAG Systems

Two types of failures are common in RAG systems.

## Retriever Failure

What happens in retriever failure is that the retriever is unable to retrieve the relevant context from the knowledge base. Many times, the chunks retrieved by the retriever are not the most relevant ones. This can lead to an incorrect answer generated by the LLM. The retriever failure generally stems from how the knowledge base is formed and how the embedded model is working. Essentially, the context generated after augmenting the prompt is more or less garbage, and as the popular saying goes in machine learning goes, "garbage in, garbage out."

## Generator Failure

What happens in generator failure is that, though the chunks retrieved are the relevant ones, the answer generated by the model is not 100% accurate. Basically the in-context learning process is improper. Sometimes what happens is the LLM is unable to understand the query given by the user, or it can also happen that the LLM cannot understand exactly the context in which the context is related to the user's query. The generator failure generally stems from what type of an LLM is being used.

# Data Flow in RAG

The knowledge source is where the journey of the data begins. A data loader then parses through this knowledge and collects the data and its associated metadata from the knowledge source. This is then further passed on to the process of chunking, where the entire knowledge source is divided into smaller chunks. You can think of this as the entire knowledge source document getting divided into smaller documents. Each chunk has the text and its associated metadata inside it. All these chunks are then passed on to the embedder model that generates an embedding vector for each chunk. This embedding vector captures the semantic meaning of the text present in a particular chunk. So at this point, what we have is, for each chunk, its associated embedding vector, the text present in that chunk, and the metadata. This information is then stored in a vector store or a vector database. Once this is done, then the user's query is given to the embedder model, which then converts that query into the same dimensional embedding vector as that of the embedding vectors that are stored in the vector store. This is the query vector. The Retriever then carries out a similarity search of the query vector with all the vectors present in the Vector Store. It then retrieves the top-$k$ most similar chunks to that of the query vector and its associated text and metadata. The text present in these retrieved chunks is then added to the query given by the user, which forms the augmented query. This augmented query is then given as input to the LLM, after which it generates the response based on the retrieved chunks.

The reason why the chunking process is important is because if we don't chunk the entire source knowledge into smaller parts, the embedded model will form a single vector corresponding to the entire document. Obviously, we won't be able to perform any filtering in this case using similarity as there is just one single vector corresponding to the entire knowledge source. On the other hand, if the entire document is chunked such that each page corresponds to a particular chunk, then the retriever can find the most similar pages to the user's query and pass the text in them as relevant context to augment the user's prompt.
