---
title: "Introduction to FastAPI"
draft: true
author: "Sushrut"
date: 2025-07-30
description: "."
categories: [FastAPI]
tags: [API, FastAPI, Blog]
format:
  html:
    link-citations: true
    smooth-scroll: true
    toc: true
    mermaid:
      theme: dark
bibliography: ../../../references/references.bib
csl: ../../../references/apa.csl
---

# What is FastAPI?

[FastAPI](https://fastapi.tiangolo.com/) is a modern, high-performance web framework for building APIs with Python, based on standard Python type hints. It is designed to make it easy and fast to build efficient, production-ready APIs, especially those involving asynchronous input/output (I/O) operations and data validation. Roughly speaking, what asynchronous means is that multiple jobs or tasks can be executed simultaneously. Fast API requires Python version 3.7+.

# Key Features of FastAPI

The FastAPI website mentions its key features as:

- Fast: Very high performance, on par with Node.js and Go (thanks to Starlette and Pydantic). One of the fastest Python frameworks available.
- Fast to code: Increase the speed to develop features by about 200% to 300%.
- Fewer bugs: Reduce about 40% of human (developer) induced errors.
- Intuitive: Great editor support. Completion everywhere. Less time debugging.
- Easy: Designed to be easy to use and learn. Less time reading docs.
- Short: Minimize code duplication. Multiple features from each parameter declaration. Fewer bugs.
- Robust: Get production-ready code. With automatic interactive documentation.
- Standards-based: Based on (and fully compatible with) the open standards for APIs: OpenAPI (previously known as Swagger) and JSON Schema.

So, broadly the features are:

1. High Performance:
   - One of the fastest Python web frameworks
   - Comparable in speed to Node.js and Go for many API tasks
2. Based on Python Type Hints:
   - Validate inputs automatically
3. Built-in Data Validation:
   - Ensures that all input data is structured, typed, and clean
4. Asynchronous Support:
   - Designed from the ground up to support `async` I/O operations
5. Easy Testing & Debugging:
   - Works great with pytest and testing tools
   - Return types are predictable and readable for debugging
6. Automatic API Documentation:
   - Built-in integration with Swagger UI (`/docs`) and ReDoc (`/redoc`)
   - Helps both backend and frontend teams explore and test endpoints easily
7. Ideal for ML & Data Science Projects:
   - Wrapping ML models as APIs (`/predict`)
   - Serving pre/post-processing logic
   - Managing model versions and feature validation
